### ISSUE TITLE
Icons aren't appearing in output.

### ISSUE THREAD

**Issue by queuebit** [jfrazelle/weather#11]
`No icon found for partly-cloudy-day.`

`weather/utilities.go` points to <https://jess.s3.amazonaws.com/weather/icons/partly-cloudy-day.txt>
```go
48:func getIcon(icon string) (iconTxt string, err error) {
51:	switch icon {
69:	uri := "https://jesss.s3.amazonaws.com/weather/icons/" + icon + ".txt"
```

Any chance the bucket name changed or you removed these from s3?

**Comment by jfrazelle** [comment]
I'll look into it

On Thursday, February 26, 2015, queuebit <notifications@github.com> wrote:

> No icon found for partly-cloudy-day.
>
> weather/utilities.go points to
> https://jess.s3.amazonaws.com/weather/icons/partly-cloudy-day.txt
>
> 48:func getIcon(icon string) (iconTxt string, err error) {51: switch icon {69: uri := "https://jesss.s3.amazonaws.com/weather/icons/" + icon + ".txt"
>
> Any chance the bucket name changed or you removed these from s3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/11>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
fixed

**Comment by queuebit** [comment]
👍 Thanks!
