### ISSUE TITLE
Why are the icons hosted?

### ISSUE THREAD

**Issue by DannyNemer** [jfrazelle/weather#13]
Why are the ASCII icons hosted on an S3 bucket, as opposed to being stored locally? I feel bad that you are charged for our usage.

Thank you.

**Comment by jfrazelle** [comment]
I didn't want to add to source don't worry my s3 bill is like 2 dollars and
I have a bunch of other stuff there

On Tuesday, April 7, 2015, Danny Nemer <notifications@github.com> wrote:

> Why are the ASCII icons hosted on an S3 bucket, as opposed to being stored
> locally? I feel bad that you are charged for our usage.
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/13>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
