### ISSUE TITLE
certificate errors all over

### ISSUE THREAD

**Issue by OliverLeitner** [jfrazelle/weather#14]
hi j.

just tried your app and getting x509 errors while trying to run it.

~/scripts/gocode/bin$ ./weather 
Http request to https://geocode.jessfraz.com/forecast failed: Post https://geocode.jessfraz.com/forecast: x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: algorithm unimplemented" while trying to verify candidate authority certificate "COMODO ECC Certification Authority")

**Comment by brunobord** [comment]
same issue here.

**Comment by jfrazelle** [comment]
probably the go version should work if you install from  source
