### ISSUE TITLE
Not displaying the location

### ISSUE THREAD

**Issue by reggi** [jfrazelle/weather#2]
Hey! Cool app!

I notice that I'm not getting my location in the output.

```
thomas@workstation:jspm-npm$ weather
                   xX:
                  .NNK
                  .NN0
     .OOc          ,:.         .d0k
     .dXNXc                   xXNXl
       .ld;   .cdOKXXX0ko;.   cd:
            :0NNKkocccoOXNXk'
          .ONNk'         :KNNd
          0NXc             kNNo
'cccc;   cNNx       .,;:cc:cXNX.   :ccc:.
xXNNX0.  oNNl   'lOXNNNNNNNNNNN0o';KNNNXc
         'XNK.cKNNKd:..    ..:dKNNKl.
       .,:0NNNNXd.              .oXNXocc:;'
   .ckXNNNNNNNO.                  .kNNNNNNNXOl.
  lXNXx;.   ..                      .    .;dXNXd
 ONNd.                                       oXN0.
dNNo                                          cNNk
XNN.                                           NNX
0NN'                                          .NNK
;XN0.                                        .ONNc
 ;XNXo.                                    .lXNX:
  .oXNX0dlcclx0Xo.              .oXKxlccldOXNXd.
     ,lk0KXXK0xKNN0o;..    ..;o0NNKx0KXXX0ko,
                'lOXNNNNNNNNNNXOo,
                    :x0XNNX0x:.

Current weather is Partly Cloudy in  in  for January 8 at 11:12am EST
The temperature is 15.66°F, but it feels like -2.2°F

Ick! The humidity is 65%
The nearest storm is 26 miles ENE away
The wind speed is 22.07 mph SE
The cloud coverage is 25%
The visibilty is 9.98 miles
The pressure is 1026.77 mbar
```

I also noticed that the [screenshot says](https://github.com/jfrazelle/weather/blob/master/screenshot.png) `in New York in New York` which should either say `in New York, New York` or just `in New York`

**Comment by jfrazelle** [comment]
Where do you live

On Thursday, January 8, 2015, Thomas Reggi <notifications@github.com> wrote:

> Hey! Cool app!
>
> I notice that I'm not getting my location in the output.
>
> thomas@workstation:jspm-npm$ weather
>                    xX:
>                   .NNK
>                   .NN0
>      .OOc          ,:.         .d0k
>      .dXNXc                   xXNXl
>        .ld;   .cdOKXXX0ko;.   cd:
>             :0NNKkocccoOXNXk'
>           .ONNk'         :KNNd
>           0NXc             kNNo
> 'cccc;   cNNx       .,;:cc:cXNX.   :ccc:.
> xXNNX0.  oNNl   'lOXNNNNNNNNNNN0o';KNNNXc
>          'XNK.cKNNKd:..    ..:dKNNKl.
>        .,:0NNNNXd.              .oXNXocc:;'
>    .ckXNNNNNNNO.                  .kNNNNNNNXOl.
>   lXNXx;.   ..                      .    .;dXNXd
>  ONNd.                                       oXN0.
> dNNo                                          cNNk
> XNN.                                           NNX
> 0NN'                                          .NNK
> ;XN0.                                        .ONNc
>  ;XNXo.                                    .lXNX:
>   .oXNX0dlcclx0Xo.              .oXKxlccldOXNXd.
>      ,lk0KXXK0xKNN0o;..    ..;o0NNKx0KXXX0ko,
>                 'lOXNNNNNNNNNNXOo,
>                     :x0XNNX0x:.
>
> Current weather is Partly Cloudy in  in  for January 8 at 11:12am EST
> The temperature is 15.66°F, but it feels like -2.2°F
>
> Ick! The humidity is 65%
> The nearest storm is 26 miles ENE away
> The wind speed is 22.07 mph SE
> The cloud coverage is 25%
> The visibilty is 9.98 miles
> The pressure is 1026.77 mbar
>
> I also noticed that the screenshot says
> <https://github.com/jfrazelle/weather/blob/master/screenshot.png> in New
> York in New York which should either say in New York, New York or just in
> New York
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/2>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by reggi** [comment]
Brooklyn / New York

**Comment by jfrazelle** [comment]
Lol how weird

On Thursday, January 8, 2015, Thomas Reggi <notifications@github.com> wrote:

> Brooklyn / New York
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/2#issuecomment-69207477>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
Brooklyn isn't a real place anyways ;)

I'll look into it this weekend

On Thursday, January 8, 2015, Jessica Frazelle <me@jessfraz.com> wrote:

> Lol how weird
>
> On Thursday, January 8, 2015, Thomas Reggi <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Brooklyn / New York
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jfrazelle/weather/issues/2#issuecomment-69207477>.
>>
>
>
> --
>
>
> Jessie Frazelle
> 4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
> pgp.mit.edu
> <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>
>
>

-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
fixed
