### ISSUE TITLE
Doesn't work anymore :( 

### ISSUE THREAD

**Issue by inadarei** [jfrazelle/weather#22]
One of the APIs the utility uses is not available, anymore: `http://www.telize.com/geoip`. From their website (as of Nov 15, 2015):

> IMPORTANT INFORMATION
> The public API will permanently shut down on November 15th, 2015. More information can be found [here](http://www.cambus.net/adventures-in-running-a-free-public-api/). To continue using Telize after this date, please spin up your own instance or subscribe to a paid plan.

**Comment by jfrazelle** [comment]
Welp I should host my own






On Sat, Nov 14, 2015 at 10:53 PM -0800, "Irakli Nadareishvili" <notifications@github.com> wrote:












One of the APIs the utility uses is not available, anymore: http://www.telize.com/geoip. From their website (as of Nov 15, 2015):




IMPORTANT INFORMATION

The public API will permanently shut down on November 15th, 2015. More information can be found here. To continue using Telize after this date, please spin up your own instance or subscribe to a paid plan.

**Comment by inadarei** [comment]
That would be great, but since you may run into the same exact problems which frustrated Frederic + lead him to shut his instance down, how about these guys https://freegeoip.net/json/

10,000 request/hour sounds plenty and since the API doesn't authenticate, they are probably throttling by IP i.e. if nobody will call the `weather` in their terminals more than 10,000 times an hour, it should work for everybody? At least until and if freegeoip shuts down too (oh, noes).

**Comment by jfrazelle** [comment]
fixed via https://github.com/jfrazelle/weather/commit/90c77de96ff7991257a2b9881ee49260148c540f
