### ISSUE TITLE
Forecast option is confusing?

### ISSUE THREAD

**Issue by marcosnils** [jfrazelle/weather#24]
![image](https://cloud.githubusercontent.com/assets/1578458/11598391/6490c956-9aa0-11e5-8d11-3908d83c4426.png)

Hey Jess, not sure if it's really an issue but I would have expected to see the forecast for Saturday and Sunday when sending `-d 2` as getting the same info twice (Friday) is irrelevant for me. 

If you think this should be changed I'm glad to submit a PR, I just wanted to check with you first. 

Thanks for the amazing tool!

**Comment by jfrazelle** [comment]
Sure thing, please submit onne :) thanks!

On Fri, Dec 4, 2015 at 11:04 AM, Marcos Nils <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1578458/11598391/6490c956-9aa0-11e5-8d11-3908d83c4426.png>
>
> Hey Jess, not sure if it's really an issue but I would have expected to
> see the forecast for Saturday and Sunday when sending -d 2 as getting the
> same info twice (Friday) irrelevant for me.
>
> If you think this should be changed I'm glad to submit a PR, I just wanted
> to check with you first.
>
> Thanks for the amazing tool!>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/24>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by marcosnils** [comment]
Fixed in #25
