### ISSUE TITLE
SSL Cert Expired?

### ISSUE THREAD

**Issue by numonium** [jfrazelle/weather#28]
Tried to run and got this error -

`Get https://telize.j3ss.co/geoip: x509: certificate has expired or is not yet valid`

Sorrrryyyy :(

**Comment by jfrazelle** [comment]
fixed

On Fri, Jul 1, 2016 at 2:03 PM, numonium <notifications@github.com> wrote:

> Tried to run and got this error -
>
> Get https://telize.j3ss.co/geoip: x509: certificate has expired or is not
> yet valid
>
> Sorrrryyyy :(
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jfrazelle/weather/issues/28>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABYNbA0oUqAiNfH7S7I7iVUAMKRbJnoSks5qRYCbgaJpZM4JDeou>
> .
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
thanks!

**Comment by ak2k** [comment]
This issue seems to have recurred.

$ weather
Get https://telize.j3ss.co/geoip: x509: certificate has expired or is not yet valid
