### ISSUE TITLE
Error decoding the response

### ISSUE THREAD

**Issue by carlosrah** [jfrazelle/weather#9]
Hi

I'm trying to execute the app but i always get this message:

Decoding the response from http://geocode.jessfraz.com/geocode failed: invalid character '<' looking for beginning of value

Any idea?

**Comment by jfrazelle** [comment]
Are you building from source? Looks like it's not hitting the https
endpoint and I updated the uploaded binaries to reflect that change as well

On Wednesday, January 21, 2015, carlosrah <notifications@github.com> wrote:

> Hi
>
> I'm trying to execute the app but i always get this message:
>
> Decoding the response from http://geocode.jessfraz.com/geocode failed:
> invalid character '<' looking for beginning of value
>
> Any idea?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/9>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by carlosrah** [comment]
No, i downloaded the linux amd64 binary.

**Comment by jfrazelle** [comment]
When did you download it? Today?

On Wed, Jan 21, 2015 at 9:53 AM, carlosrah <notifications@github.com> wrote:

> No, i downloaded the linux amd64 binary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/9#issuecomment-70886604>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by carlosrah** [comment]
Yeah, about 2 hours ago

**Comment by jfrazelle** [comment]
I can't reproduce with the binary here
https://jesss.s3.amazonaws.com/weather/binaries/linux/amd64/weather can you
try passing your location manually

On Wed, Jan 21, 2015 at 9:58 AM, carlosrah <notifications@github.com> wrote:

> Yeah, about 2 hours ago
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/9#issuecomment-70887395>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by carlosrah** [comment]
Downloaded the binary again from the url https://jesss.s3.amazonaws.com/weather/binaries/linux/amd64/weather and passed location as parameter (-l "Paris, France") the result is the same.

Will try to build it from sources later

**Comment by jfrazelle** [comment]
hmmm I am seeing it now, the API response from the google geocode response
may have changed from 6 months ago when I wrote this, I also need some sort
of debug logs added, sorry this is an old project that needs some love,
didn't expect it to get so much attention

On Wed, Jan 21, 2015 at 11:34 AM, carlosrah <notifications@github.com>
wrote:

> Downloaded the binary again from the url
> https://jesss.s3.amazonaws.com/weather/binaries/linux/amd64/weather and
> passed location as parameter (-l "Paris, France") the result is the same.
>
> Will try to build it from sources later
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/9#issuecomment-70905532>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by carlosrah** [comment]
No problem. i like the idea behind the app and will use it to learn about this language

Thanks for your time...

**Comment by codingsince1985** [comment]
Hi Jessie, I reckon something wrong with your Google Maps API key.

**Comment by jfrazelle** [comment]
Probably being rate limited

On Thursday, January 22, 2015, Jerry Zhao <notifications@github.com> wrote:

> Hi Jessie, I reckon something wrong with your Google Maps API key.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jfrazelle/weather/issues/9#issuecomment-71002446>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by jfrazelle** [comment]
fixed
